export const LOGIN_USER = "LOGIN_USER";

export const GET_SYMBOLS_REQUEST = "GET_SYMBOLS_REQUEST";
export const GET_SYMBOLS_SUCCESS = "GET_SYMBOLS_SUCCESS";
export const GET_SYMBOLS_FAILURE = "GET_SYMBOLS_FAILURE";

export const GET_CURRENCY_INFO_REQUEST = "GET_CURRENCY_INFO_REQUEST";
export const GET_CURRENCY_INFO_SUCCESS = "GET_CURRENCY_INFO_SUCCESS";
export const GET_CURRENCY_INFO_FAILURE = "GET_CURRENCY_INFO_FAILURE";

export const GET_DETAILS_REQUEST = "GET_DETAILS_REQUEST";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_INFO = "GET_DETAILS_INFO";
export const GET_DETAILS_RESET = "GET_DETAILS_RESET";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
